require('dotenv').config({ path: '../.env' });
const mongoose = require('mongoose');
const AITool = require('./models/AITool');

// Tools to INSERT (only if name doesn't exist yet)
const newTools = [
  // ── CHATBOT / LLMs ────────────────────────────────────────────────────────
  { name: 'Grok',               url: 'https://grok.x.ai',                   category: 'chatbot',      description: 'Asistente IA de xAI (Elon Musk) con acceso en tiempo real a X (Twitter), ideal para analizar tendencias y noticias. Se hizo conocido por ser el primer modelo IA integrado en una red social masiva y por su tono directo sin censuras.' },
  { name: 'Meta AI',            url: 'https://www.meta.ai',                  category: 'chatbot',      description: 'Asistente IA de Meta integrado en WhatsApp, Instagram y Facebook, basado en Llama. Se hizo conocido por tener la mayor distribución instantánea del mundo al llegar a más de 3 mil millones de usuarios desde su lanzamiento.' },
  { name: 'DeepSeek',           url: 'https://www.deepseek.com',             category: 'chatbot',      description: 'Modelo de lenguaje chino con capacidades comparables a GPT-4 a una fracción del costo, con versiones open source. Se hizo conocido en enero 2025 cuando su lanzamiento hizo caer las acciones de empresas tech en Wall Street.' },
  { name: 'Coze',               url: 'https://www.coze.com',                 category: 'chatbot',      description: 'Plataforma de ByteDance para construir agentes IA personalizados con memoria, plugins y acceso a internet sin código. Se hizo conocida por ofrecer capacidades avanzadas de agentes IA de forma completamente gratuita.' },
  { name: 'Poe',                url: 'https://poe.com',                      category: 'chatbot',      description: 'Plataforma de Quora que agrega múltiples modelos IA: GPT-4, Claude, Gemini, Llama y más en un solo lugar. Se hizo conocida por ser la forma más fácil de acceder y comparar todos los modelos líderes con una sola suscripción.' },
  { name: 'Le Chat',            url: 'https://chat.mistral.ai',              category: 'chatbot',      description: 'Interfaz conversacional de Mistral AI con acceso a sus modelos de última generación, búsqueda web en tiempo real y procesamiento de documentos. Se hizo conocida por ofrecer velocidades de respuesta récord siendo la alternativa europea a ChatGPT.' },
  { name: 'Qwen',               url: 'https://qwenlm.github.io',             category: 'chatbot',      description: 'Serie de modelos open source de Alibaba con capacidades multimodales que compiten con GPT-4 y Claude. Se hizo conocido por ser el modelo open source chino con mejor rendimiento y disponibilidad gratuita para uso comercial.' },
  { name: 'Microsoft Copilot',  url: 'https://copilot.microsoft.com',        category: 'productivity', description: 'IA integrada en todo el ecosistema Microsoft: Word, Excel, PowerPoint, Teams y Outlook. Se hizo conocido por ser la apuesta más agresiva de Microsoft para monetizar su inversión de 13 mil millones de dólares en OpenAI.' },
  { name: 'Gemini Flash',       url: 'https://ai.google.dev',                category: 'chatbot',      description: 'Modelo multimodal de Google ultraveloz capaz de procesar texto, imágenes, audio y video simultáneamente a bajo costo. Se hizo conocido por ofrecer capacidades de Gemini Pro a velocidad casi instantánea, adoptado masivamente por desarrolladores.' },

  // ── AGENTES IA ────────────────────────────────────────────────────────────
  { name: 'Manus AI',           url: 'https://manus.im',                     category: 'other',        description: 'Agente IA autónomo capaz de navegar la web, ejecutar código, gestionar archivos y completar tareas complejas sin intervención humana. Se hizo conocido en 2025 cuando sus demos virales generaron listas de espera de decenas de miles de personas.' },
  { name: 'OpenAI Operator',    url: 'https://openai.com/operator',          category: 'other',        description: 'Agente IA de OpenAI que opera un navegador de forma autónoma: compra productos, rellena formularios, hace reservas y navega sitios como un humano. Se hizo conocido por ser el primer agente de uso general que ejecuta tareas reales en internet.' },
  { name: 'LangGraph Cloud',    url: 'https://langchain.com/langgraph',      category: 'other',        description: 'Plataforma para construir y desplegar agentes IA con estado persistente y flujos complejos de decisión en múltiples pasos. Se hizo conocida por resolver el problema de mantener contexto y estado a lo largo de tareas largas con LLMs.' },
  { name: 'Cognition Devin',    url: 'https://cognition.ai',                 category: 'code',         description: 'Considerado el primer ingeniero de software IA completamente autónomo, capaz de planificar, escribir, depurar y desplegar proyectos sin ayuda humana. Se hizo mundialmente conocido cuando su demo completando un proyecto completo generó debates sobre el futuro del empleo tech.' },

  // ── VIDEO ─────────────────────────────────────────────────────────────────
  { name: 'Seedance',           url: 'https://seedance.ai',                  category: 'video',        description: 'Generador de video IA de ByteDance con calidad cinematográfica, movimientos de cámara precisos y consistencia de personajes sobresaliente. Se hizo conocido cuando sus videos superaron visualmente a Runway y Kling viralizándose en redes.' },
  { name: 'Wan 2.1',            url: 'https://wanvideo.ai',                  category: 'video',        description: 'Modelo de generación de video de código abierto de Alibaba, considerado el mejor open source en su categoría. Se hizo conocido por poder descargarse y correrse localmente, democratizando la generación de video sin suscripciones.' },
  { name: 'Vidu AI',            url: 'https://www.vidu.io',                  category: 'video',        description: 'Generador de video IA chino con capacidad para mantener consistencia de personajes a lo largo de escenas hasta 16 segundos. Se hizo conocido por sus demos mostrando personajes con rasgos físicos consistentes entre escenas.' },
  { name: 'Hailuo AI',          url: 'https://hailuoai.com',                 category: 'video',        description: 'Generador de video IA de MiniMax con movimientos de cámara cinematográficos y expresiones faciales muy realistas. Se hizo conocido cuando sus videos empezaron a circular en redes siendo confundidos con producciones reales.' },
  { name: 'Veo 2',              url: 'https://deepmind.google/technologies/veo', category: 'video',   description: 'Modelo de generación de video de Google DeepMind con comprensión profunda de física, movimiento de cámara y coherencia visual. Se hizo conocido por ser el primer modelo que entiende la física real, generando agua, humo y movimiento de forma creíble.' },
  { name: 'Pixverse AI',        url: 'https://pixverse.ai',                  category: 'video',        description: 'Generador de video IA con efectos especiales, transiciones y estilos cinematográficos accesibles desde el navegador. Se hizo conocido por su generosidad en el plan gratuito y la calidad de sus efectos de transformación.' },
  { name: 'Viggle AI',          url: 'https://viggle.ai',                    category: 'video',        description: 'Inserta cualquier personaje en videos con movimientos realistas y consistencia visual entre escenas. Se hizo conocido cuando creadores lo usaron para animar personajes de anime en coreografías que se volvieron virales.' },
  { name: 'Higgsfield AI',      url: 'https://higgsfield.ai',                category: 'video',        description: 'Genera videos con control preciso sobre movimientos de cámara y físicas realistas, fundado por ex-ingenieros de Snap. Se hizo conocido por el nivel de control cinematográfico que ofrece y la trayectoria técnica de su equipo.' },
  { name: 'Haiper AI',          url: 'https://haiper.ai',                    category: 'video',        description: 'Generador de video IA fundado por ex-investigadores de Google DeepMind, con videos fluidos y alta consistencia visual. Se hizo conocido por la trayectoria técnica de su equipo fundador y la calidad de sus outputs.' },
  { name: 'Skyreels AI',        url: 'https://skyreels.ai',                  category: 'video',        description: 'Genera videos de duración extendida manteniendo coherencia narrativa y visual entre escenas. Se hizo conocido por resolver el mayor problema de los generadores de video: la consistencia a lo largo del tiempo.' },
  { name: 'Invideo AI',         url: 'https://invideo.io',                   category: 'video',        description: 'Plataforma completa para crear videos de YouTube, redes sociales y anuncios desde un prompt de texto, generando guión, voz en off y montaje completo. Se hizo conocido entre creadores por producir videos listos para publicar en minutos.' },
  { name: 'Captions AI',        url: 'https://www.captions.ai',              category: 'video',        description: 'App móvil IA para creadores que edita videos automáticamente, añade subtítulos animados y corrige el eye contact a cámara. Se hizo conocida porque su función de corrección de mirada a cámara era antes exclusiva de software profesional de miles de dólares.' },
  { name: 'Hedra',              url: 'https://www.hedra.com',                category: 'video',        description: 'Genera videos con avatares parlantes a partir de una imagen y audio, con sincronización labial perfecta y expresiones faciales naturales. Se hizo conocida cuando creadores comenzaron a dar vida a personajes ilustrados y fotografías históricas.' },
  { name: 'D-ID',               url: 'https://www.d-id.com',                 category: 'video',        description: 'Plataforma de avatares digitales parlantes que anima fotos y crea presentadores IA con sincronización labial en múltiples idiomas. Se hizo conocida por ser pionera en la tecnología de talking heads y su uso en educación y corporativo.' },
  { name: 'Opus Clip',          url: 'https://www.opus.pro',                 category: 'video',        description: 'Convierte videos largos en clips cortos virales para TikTok, Reels y YouTube Shorts automáticamente detectando los momentos más impactantes. Se hizo conocido entre creadores por ahorrar horas de edición manual con resultados de alta calidad.' },
  { name: 'Fliki',              url: 'https://fliki.ai',                     category: 'video',        description: 'Convierte artículos, blogs y scripts en videos con voz en off IA y clips visuales automáticos sin grabar nada. Se hizo conocido entre marketers y bloggers por transformar contenido escrito en video de forma instantánea.' },
  { name: 'Pictory AI',         url: 'https://pictory.ai',                   category: 'video',        description: 'Transforma guiones y artículos largos en videos profesionales con imágenes, subtítulos y música automáticos. Se hizo conocido en el mundo del video marketing por la rapidez con que genera contenido listo para publicar.' },

  // ── IMAGEN ────────────────────────────────────────────────────────────────
  { name: 'Recraft',            url: 'https://www.recraft.ai',               category: 'image',        description: 'Generador de imágenes IA especializado en diseño vectorial, iconos, ilustraciones y branding con control estilístico muy preciso. Se hizo conocida cuando su modelo V3 encabezó los rankings de Hugging Face superando a Midjourney y DALL-E en benchmarks especializados.' },
  { name: 'Magnific AI',        url: 'https://magnific.ai',                  category: 'image',        description: 'Herramienta de upscaling de imágenes que añade detalles coherentes y realistas al ampliar, no solo aumenta la resolución. Se hizo conocida cuando diseñadores viralizaron comparativas mostrando cómo transformaba imágenes borrosas en fotografías de alta definición.' },
  { name: 'Krea AI',            url: 'https://www.krea.ai',                  category: 'image',        description: 'Plataforma de generación y edición de imágenes con IA en tiempo real que muestra los resultados mientras escribes el prompt. Se hizo conocida por su función de generación en vivo donde la imagen se forma conforme escribes.' },
  { name: 'Playground AI',      url: 'https://playground.com',               category: 'image',        description: 'Generador de imágenes IA con modelos propios de alta calidad y editor integrado para modificar partes específicas de las imágenes. Se hizo conocido por su plan gratuito generoso y sus modelos especializados en imágenes fotorrealistas.' },
  { name: 'Civitai',            url: 'https://civitai.com',                  category: 'image',        description: 'Comunidad y plataforma para compartir, descargar y usar modelos de Stable Diffusion personalizados por la comunidad. Se hizo conocida por ser el hub más grande del mundo de modelos IA de imagen open source con miles de estilos especializados.' },
  { name: 'Napkin AI',          url: 'https://www.napkin.ai',                category: 'other',        description: 'Convierte texto e ideas en diagramas, infografías y visualizaciones automáticamente con IA. Se hizo conocida por resolver el problema de transformar explicaciones escritas en visuales profesionales sin saber diseñar.' },
  { name: 'Photoroom',          url: 'https://www.photoroom.com',            category: 'image',        description: 'Editor de fotos IA especializado en producto y ecommerce que elimina fondos y genera escenas profesionales instantáneamente. Se hizo conocido cuando tiendas online comenzaron a usarlo para generar fotos de catálogo sin necesitar fotógrafo.' },
  { name: 'Clipdrop',           url: 'https://clipdrop.co',                  category: 'image',        description: 'Suite de herramientas IA para edición de imágenes: eliminar objetos, cambiar fondos, mejorar iluminación y upscaling. Se hizo conocida por su función de reimagine que cambia completamente el fondo de una foto con solo describir el texto.' },
  { name: 'Flair AI',           url: 'https://flair.ai',                     category: 'image',        description: 'Genera fotos de producto con escenarios y ambientaciones profesionales a partir de una simple foto del artículo. Se hizo conocida en el sector ecommerce por eliminar la necesidad de sesiones fotográficas costosas.' },
  { name: 'Artbreeder',         url: 'https://www.artbreeder.com',           category: 'image',        description: 'Mezcla y evoluciona imágenes con IA para crear retratos, paisajes y personajes únicos de forma colaborativa. Se hizo conocida por ser una de las primeras plataformas creativas IA con comunidad activa antes de la era Midjourney.' },
  { name: 'NightCafe',          url: 'https://creator.nightcafe.studio',     category: 'image',        description: 'Generador de arte IA con múltiples modelos y comunidad activa de artistas digitales que comparten y votan creaciones. Se hizo conocida por ser una de las primeras en hacer accesible el arte IA con sistema de créditos gratuitos.' },

  // ── CÓDIGO ────────────────────────────────────────────────────────────────
  { name: 'Lovable',            url: 'https://lovable.dev',                  category: 'code',         description: 'Genera aplicaciones web completas y funcionales desde una descripción en lenguaje natural, con frontend, backend y base de datos incluidos. Se hizo conocida cuando sus demos mostraban personas sin conocimientos técnicos construyendo startups completas en horas.' },
  { name: 'Windsurf',           url: 'https://codeium.com/windsurf',         category: 'code',         description: 'Editor de código IA con agente Cascade que entiende el contexto completo del proyecto y edita múltiples archivos simultáneamente. Se hizo conocido como el competidor más serio de Cursor, con muchos desarrolladores migrando por su velocidad y precisión.' },
  { name: 'Phind',              url: 'https://www.phind.com',                category: 'code',         description: 'Motor de búsqueda IA especializado en programación que combina búsqueda web con generación de código y explicaciones técnicas detalladas. Se hizo conocido entre desarrolladores por dar respuestas con código funcional y actualizado, superando a Stack Overflow en muchos casos.' },
  { name: 'Aider',              url: 'https://aider.chat',                   category: 'code',         description: 'Asistente de código IA que corre en terminal, edita archivos reales del proyecto y hace commits automáticos en Git. Se hizo conocido entre power users por integrarse directamente en el flujo de trabajo sin necesidad de un IDE.' },
  { name: 'Continue.dev',       url: 'https://continue.dev',                 category: 'code',         description: 'Extensión open source para VS Code y JetBrains que conecta cualquier modelo IA como asistente de código local o en la nube. Se hizo conocida por ofrecer una alternativa open source y privada a GitHub Copilot.' },

  // ── AUDIO Y MÚSICA ────────────────────────────────────────────────────────
  { name: 'Sesame AI',          url: 'https://www.sesame.com',               category: 'audio',        description: 'Sistema de voz conversacional IA con naturalidad y fluidez emocional sin precedentes, capaz de mantener conversaciones en tiempo real que suenan completamente humanas. Se hizo conocido cuando sus demos generaron una respuesta viral masiva siendo descrita como inquietantemente humana.' },
  { name: 'Stable Audio',       url: 'https://www.stableaudio.com',          category: 'audio',        description: 'Generador de música y efectos de sonido IA de Stability AI con control sobre duración, estilo e instrumentación hasta 3 minutos. Se hizo conocido por ser el primer generador que producía música de calidad de estudio lista para proyectos profesionales.' },
  { name: 'Boomy',              url: 'https://boomy.com',                    category: 'audio',        description: 'Crea canciones originales con IA en segundos y permite publicarlas directamente en Spotify y Apple Music generando regalías. Se hizo conocida por ser la primera herramienta que permitía a cualquier persona sin talento musical publicar música propia y monetizarla.' },
  { name: 'Mubert',             url: 'https://mubert.com',                   category: 'audio',        description: 'Genera música ambiental y funcional con IA en tiempo real adaptada al mood, actividad o contenido especificado. Se hizo conocida entre creadores por generar música libre de derechos perfectamente adaptada a videos, podcasts y streams.' },
  { name: 'Soundraw',           url: 'https://soundraw.io',                  category: 'audio',        description: 'Genera música original libre de derechos con IA seleccionando mood, género y duración con control total sobre la composición. Se hizo conocida entre creadores de YouTube y TikTok por generar tracks únicos que nunca dan problemas de copyright.' },
  { name: 'Aiva',               url: 'https://www.aiva.ai',                  category: 'audio',        description: 'Compone música orquestal y cinematográfica con IA, usada en videojuegos, películas y anuncios. Se hizo conocida por ser una de las primeras IAs reconocida oficialmente como compositora por una sociedad de derechos de autor.' },

  // ── PRODUCTIVIDAD ─────────────────────────────────────────────────────────
  { name: 'NotebookLM',         url: 'https://notebooklm.google.com',        category: 'productivity', description: 'Asistente de investigación IA de Google que analiza documentos propios y crea podcasts de audio con dos voces conversando sobre tu contenido. Se hizo viral cuando su función de generar podcasts desde tus propios documentos sorprendió a millones por su naturalidad.' },
  { name: 'Granola',            url: 'https://www.granola.ai',               category: 'productivity', description: 'Notetaker IA para Mac que escucha reuniones en segundo plano y genera notas estructuradas sin necesitar un bot en la llamada. Se hizo conocida porque funciona con cualquier app de videollamadas sin instalar nada en la reunión.' },
  { name: 'Limitless AI',       url: 'https://www.limitless.ai',             category: 'productivity', description: 'Dispositivo y app IA que graba y transcribe todo lo que escuchas durante el día para buscarlo y recordarlo después. Se hizo conocida por su wearable que actúa como memoria externa humana aumentada.' },
  { name: 'Superhuman AI',      url: 'https://superhuman.com',               category: 'productivity', description: 'Cliente de email con IA que triagea la bandeja de entrada, redacta respuestas y permite procesar emails a velocidad récord. Se hizo conocido por su modelo de invitación exclusiva y usuarios reportando procesar su inbox completo en menos de 30 minutos.' },
  { name: 'Taskade AI',         url: 'https://www.taskade.com',              category: 'productivity', description: 'Plataforma con agentes IA que gestionan proyectos, generan tareas, crean documentos y automatizan flujos de trabajo en equipo. Se hizo conocida por integrar agentes IA autónomos directamente dentro de un gestor de proyectos.' },

  // ── INVESTIGACIÓN ─────────────────────────────────────────────────────────
  { name: 'You.com',            url: 'https://you.com',                      category: 'research',     description: 'Motor de búsqueda IA que combina resultados web en tiempo real con chat, generación de imágenes y ejecución de código en una sola interfaz. Se hizo conocido por ser una alternativa directa a Google con IA nativa, sin anuncios y con respuestas sintetizadas.' },
  { name: 'Morphic',            url: 'https://www.morphic.sh',               category: 'research',     description: 'Motor de búsqueda IA de código abierto que muestra el proceso de investigación en tiempo real con fuentes verificables. Se hizo conocido en la comunidad tech por su transparencia en el proceso de búsqueda y por ser completamente open source.' },
];

// Enriched descriptions for EXISTING tools (update if already exists)
const updates = [
  { name: 'ChatGPT',        description: 'Asistente conversacional de OpenAI lanzado en noviembre 2022, ideal para redacción, análisis, código y respuestas generales. Se hizo conocido por ser el producto de consumo en crecer más rápido de la historia, alcanzando 100 millones de usuarios en solo 2 meses y detonando la carrera global de la IA.' },
  { name: 'Claude',         description: 'Asistente IA de Anthropic destacado en análisis de documentos largos, razonamiento y escritura de alta calidad. Se hizo conocido por ser el modelo con mayor ventana de contexto del mercado y el más citado por escritores y analistas por su prosa de calidad superior.' },
  { name: 'Gemini',         description: 'IA conversacional de Google con capacidad multimodal e integración con el ecosistema Google. Se hizo conocido por ser la respuesta directa de Google a ChatGPT y por procesar texto, imágenes, audio y video en un solo modelo nativo.' },
  { name: 'Mistral',        description: 'Modelos de lenguaje de código abierto y alta performance de la startup francesa Mistral AI. Se hizo conocido por ser el primer modelo open source europeo que igualó a GPT-4 en benchmarks, convirtiéndose en el orgullo de la IA europea.' },
  { name: 'Perplexity',     description: 'Motor de búsqueda IA que proporciona respuestas precisas con fuentes citadas en tiempo real. Se hizo conocido por ser el "Google killer" favorito de Silicon Valley y por alcanzar 10 millones de usuarios activos diarios siendo usado por CEOs y académicos como primera fuente de información.' },
  { name: 'Midjourney',     description: 'Generador de imágenes IA conocido por su calidad artística y estética visual excepcional. Se hizo conocido cuando sus imágenes ganaron un concurso de arte oficial en Colorado en 2022, generando un debate mundial sobre IA y creatividad artística.' },
  { name: 'DALL-E',         description: 'Modelo de generación de imágenes de OpenAI integrado en ChatGPT, preciso con instrucciones complejas. Se hizo conocido por ser el primer generador de imágenes IA masivo del mundo y por popularizar el concepto de "texto a imagen" entre el público general.' },
  { name: 'Stable Diffusion', description: 'Modelo de difusión de imágenes de código abierto, altamente personalizable y descargable localmente. Se hizo conocido por ser el primer modelo de imagen IA open source de calidad profesional, liberando la generación de imágenes para que cualquiera pudiera correrlo en su PC.' },
  { name: 'Firefly',        description: 'Generador de imágenes IA de Adobe integrado con Creative Cloud, ideal para diseño profesional. Se hizo conocido por ser el primer generador de imágenes IA entrenado solo con contenido con licencia, ofreciendo seguridad legal total a diseñadores profesionales y agencias.' },
  { name: 'Leonardo AI',    description: 'Plataforma de generación de imágenes con modelos especializados para juegos, arte y diseño. Se hizo conocida por su comunidad masiva de artistas de videojuegos y por ofrecer modelos fine-tuned para concept art, personajes y escenarios gaming.' },
  { name: 'Ideogram',       description: 'Generador de imágenes IA con excelente capacidad para incluir texto legible dentro de las imágenes. Se hizo conocido por resolver el mayor punto débil de todos los generadores de imagen: escribir texto coherente y legible en las imágenes generadas.' },
  { name: 'Flux',           description: 'Modelo de generación de imágenes de Black Forest Labs creado por los fundadores originales de Stable Diffusion. Se hizo conocido porque sus imágenes son prácticamente indistinguibles de fotografías reales, superando a Midjourney y DALL-E en benchmarks de realismo.' },
  { name: 'Runway',         description: 'Suite de herramientas IA para creación de video, incluye generación texto-a-video y edición avanzada. Se hizo conocido por ser usado en producciones de Hollywood y ganar un Emmy, siendo la herramienta de referencia de cineastas y directores creativos.' },
  { name: 'Sora',           description: 'Modelo de generación de video de OpenAI capaz de crear clips realistas de hasta un minuto. Se hizo mundialmente conocido cuando sus primeros demos en febrero 2024 impactaron al mundo entero por la calidad cinematográfica nunca vista en generación de video IA.' },
  { name: 'ElevenLabs',     description: 'Síntesis y clonación de voz IA ultra realista con soporte multiidioma y control emocional. Se hizo conocido cuando actores de Hollywood lo adoptaron para doblaje y cuando su tecnología de clonación de voz demostró que cualquier voz podía reproducirse con solo 1 minuto de audio.' },
  { name: 'Suno',           description: 'Genera canciones completas con letras y música a partir de una descripción de texto. Se hizo conocido cuando millones de usuarios sin ningún conocimiento musical comenzaron a crear canciones completas y profesionales en segundos, viralizando sus creaciones.' },
  { name: 'Udio',           description: 'Creador de música IA con alta calidad de producción y control sobre género y estilo. Se hizo conocido por la calidad de producción de sus outputs, comparables a discos profesionales, y por su colaboración con artistas de la industria musical.' },
  { name: 'GitHub Copilot', description: 'Asistente de código IA de GitHub/OpenAI integrado en el editor, sugiere líneas y funciones completas en tiempo real. Se hizo conocido por ser el primer asistente de código IA adoptado masivamente por la industria, cambiando para siempre cómo los desarrolladores escriben código.' },
  { name: 'Cursor',         description: 'Editor de código con IA integrada que permite editar proyectos enteros con instrucciones en lenguaje natural. Se hizo conocido como el favorito de los desarrolladores indie y startups por su capacidad de entender proyectos completos y ser el primer IDE que realmente desafió a VS Code.' },
  { name: 'Tabnine',        description: 'Autocompletado de código IA compatible con múltiples lenguajes e IDEs, enfocado en privacidad y despliegue local. Se hizo conocido por ser la alternativa enterprise a GitHub Copilot favorita de empresas que no pueden enviar su código a la nube.' },
  { name: 'Codeium',        description: 'Extensión de autocompletado de código IA gratuita con soporte para más de 70 lenguajes. Se hizo conocida por ofrecer las mismas capacidades de GitHub Copilot completamente gratis, siendo adoptada por millones de estudiantes y desarrolladores.' },
  { name: 'Jasper',         description: 'Plataforma de contenido IA para marketing con plantillas para anuncios, blogs y redes sociales. Se hizo conocida por ser la primera herramienta de copywriting IA en alcanzar una valoración de unicornio (1.5 mil millones de dólares), siendo el estándar de agencias de marketing.' },
  { name: 'Copy.ai',        description: 'Generador de copy para marketing con plantillas para emails, landing pages y publicaciones sociales. Se hizo conocido por ser uno de los primeros en el mercado de escritura IA y por su modelo freemium que permitió a millones de emprendedores generar copy profesional sin presupuesto.' },
  { name: 'Writesonic',     description: 'Herramienta de escritura IA con generación de artículos, paráfrasis y optimización SEO integrada. Se hizo conocida por incluir un agente de búsqueda web que genera artículos actualizados con información en tiempo real, superando el límite de conocimiento de los LLMs.' },
  { name: 'Grammarly',      description: 'Asistente de escritura que corrige gramática, estilo y tono con sugerencias impulsadas por IA. Se hizo conocido por ser la herramienta de escritura más usada del mundo con más de 30 millones de usuarios diarios, siendo el estándar de redacción profesional en inglés.' },
  { name: 'Notion AI',      description: 'IA integrada en Notion para redactar, resumir, traducir y gestionar información en notas y documentos. Se hizo conocida por ser la primera integración de IA dentro de un gestor de conocimiento, mostrando cómo la IA puede mejorar todo un sistema de trabajo personal.' },
  { name: 'Otter.ai',       description: 'Transcripción automática de reuniones en tiempo real con resúmenes y puntos clave generados por IA. Se hizo conocido por ser el notetaker de reuniones más popular del mundo, adoptado por Fortune 500 y siendo la herramienta que popularizó la transcripción en tiempo real.' },
  { name: 'Surfer SEO',     description: 'Optimiza contenido para SEO con IA analizando los artículos mejor rankeados para cada keyword. Se hizo conocido por ser el estándar de la industria SEO, con agencias de todo el mundo usándolo para garantizar que su contenido rankee en la primera página de Google.' },
  { name: 'Canva AI',       description: 'Herramientas IA integradas en Canva: generación de imágenes, texto, presentaciones y fondos mágicos. Se hizo conocido por llevar el poder de la IA generativa a los 170 millones de usuarios de Canva, haciendo que crear diseños profesionales sea accesible para cualquier persona.' },
  { name: 'HubSpot AI',     description: 'Herramientas IA integradas en HubSpot para email marketing, CRM, chatbots y generación de leads. Se hizo conocido por integrar IA en todo el CRM de ventas y marketing más usado del mundo, automatizando flujos que antes requerían equipos enteros.' },
  { name: 'Tableau AI',     description: 'Plataforma de visualización de datos con IA para descubrir insights y generar análisis automáticos. Se hizo conocida por ser el estándar de business intelligence empresarial y por su función Einstein Copilot que permite hacer preguntas sobre datos en lenguaje natural.' },
  { name: 'Elicit',         description: 'Asistente de investigación IA que extrae y resume información de papers científicos automáticamente. Se hizo conocido entre investigadores y académicos por reducir semanas de revisión de literatura científica a horas, siendo adoptado por universidades de todo el mundo.' },
  { name: 'Cohere',         description: 'Plataforma de IA empresarial con modelos de lenguaje para búsqueda semántica y clasificación de texto. Se hizo conocida por ser la alternativa enterprise a OpenAI favorita de compañías que necesitan IA con privacidad de datos, despliegue propio y SLA empresarial.' },
  { name: 'Zapier AI',      description: 'Automatización de flujos de trabajo con IA que conecta más de 6,000 aplicaciones sin código. Se hizo conocido por ser la herramienta de automatización más usada del mundo y por ser el primero en integrar agentes IA que razonan y toman decisiones dentro de los flujos automatizados.' },
  { name: 'Replit AI',      description: 'Entorno de desarrollo con IA que ayuda a generar, depurar y desplegar código directamente en el navegador. Se hizo conocido entre estudiantes y principiantes por eliminar completamente la barrera de configurar un entorno de desarrollo, permitiendo programar desde cualquier dispositivo.' },
  { name: 'Pika Labs',      description: 'Herramienta de generación y edición de video IA con interfaz amigable para creadores. Se hizo conocida por su accesibilidad y por viralizarse cuando creadores comenzaron a generar clips de alta calidad desde el navegador sin instalaciones ni conocimientos técnicos.' },
  { name: 'Synthesia',      description: 'Crea videos con avatares IA que hablan en más de 120 idiomas, ideal para formación corporativa. Se hizo conocida por ser la herramienta preferida de empresas Fortune 500 para crear contenido de entrenamiento y comunicación interna sin cámaras ni actores.' },
  { name: 'HeyGen',         description: 'Plataforma de videos con avatares IA y clonación de voz para marketing y comunicación. Se hizo conocida cuando MrBeast y otros grandes creadores la usaron para doblar sus videos a múltiples idiomas manteniendo su propia voz y movimientos labiales.' },
  { name: 'Adobe Podcast',  description: 'Mejora la calidad de audio de podcasts con IA, eliminando ruido y mejorando la voz automáticamente. Se hizo conocido cuando su función "Enhance Speech" se volvió viral al transformar grabaciones de baja calidad en audio de estudio profesional con un solo clic.' },
  { name: 'ElevenLabs',     description: 'Síntesis y clonación de voz IA ultra realista con soporte multiidioma y control emocional. Se hizo conocido cuando actores de Hollywood lo adoptaron y cuando su clonación de voz demostró que cualquier voz podía reproducirse con solo 1 minuto de audio de muestra.' },
  { name: 'Midjourney',     description: 'Generador de imágenes IA conocido por su calidad artística y estética visual excepcional. Se hizo conocido cuando una imagen generada con Midjourney ganó el primer lugar en un concurso de arte oficial en Colorado en 2022, detonando el debate global sobre IA y creatividad.' },
  { name: 'v0 by Vercel',   description: 'Genera componentes de UI en React y código frontend a partir de descripciones de texto. Se hizo conocido entre diseñadores y frontend developers por generar interfaces completas y funcionales desde una descripción, cambiando el prototipado web para siempre.' },
  { name: 'Bolt.new',       description: 'Genera y despliega aplicaciones web completas desde una descripción en lenguaje natural. Se hizo conocido por ser la herramienta más accesible para construir apps sin código, viralizándose entre emprendedores que lanzaron proyectos reales en pocas horas.' },
  { name: 'Hugging Face',   description: 'Hub de modelos IA de código abierto con miles de modelos, datasets y espacios de demostración. Se hizo conocido por ser el "GitHub de la IA", siendo el lugar donde todos los laboratorios e investigadores del mundo publican sus modelos open source.' },
  { name: 'Gamma App',      description: 'Crea presentaciones, documentos y páginas web con IA de forma rápida y visualmente atractiva. Se hizo conocido por generar presentaciones completas en segundos, viralizándose cuando usuarios mostraban cómo creaba decks de inversor listos en menos de 5 minutos.' },
  { name: 'Murf AI',        description: 'Generador de voz en off IA con más de 120 voces en múltiples idiomas para presentaciones y podcasts. Se hizo conocido en el mundo de los creadores de cursos y podcasters por ofrecer voces ultra realistas a una fracción del costo de un locutor profesional.' },
  { name: 'Speechify',      description: 'Convierte textos, PDFs y webs en audio con voces IA naturales para escuchar en cualquier lugar. Se hizo conocido por ser la herramienta de accesibilidad preferida de personas con dislexia y por viralizarse en TikTok cuando usuarios mostraban cómo escuchaban libros a 4x velocidad.' },
  { name: 'Descript',       description: 'Editor de audio y video basado en transcripción con herramientas IA para eliminar muletillas. Se hizo conocido por su función "overdub" de clonación de voz y por ser el primero en permitir editar video simplemente editando su transcripción como un documento de texto.' },
  { name: 'Fireflies.ai',   description: 'Notetaker IA para reuniones que transcribe, resume y permite buscar dentro de las conversaciones. Se hizo conocido por ser el bot de notas más adoptado en Zoom y Meet, con más de 300,000 empresas usándolo para no perder ningún acuerdo ni acción de reunión.' },
  { name: 'Loom AI',        description: 'Grabación de pantalla con IA que genera títulos, resúmenes y capítulos automáticamente. Se hizo conocido por ser la herramienta de comunicación asíncrona favorita de equipos remotos y por su crecimiento viral durante la pandemia cuando las videollamadas se saturaron.' },
  { name: 'Remove.bg',      description: 'Elimina el fondo de imágenes automáticamente con IA en segundos con alta precisión. Se hizo conocido por ser literalmente viral al resolver en 1 clic algo que antes tomaba 30 minutos en Photoshop, siendo usado más de 150 millones de veces al mes.' },
  { name: 'Picsart AI',     description: 'Plataforma de edición de imágenes y video con herramientas IA para remover fondos, generar y editar. Se hizo conocida por ser la app de edición de fotos IA más descargada del mundo con más de 150 millones de usuarios activos mensuales.' },
  { name: 'Lensa AI',       description: 'Edita retratos y crea avatares artísticos con IA a partir de tus propias fotos. Se hizo conocida cuando su función de "magic avatars" generó retratos artísticos ultra detallados y se convirtió en la app más descargada del mundo durante semanas en diciembre 2022.' },
  { name: 'Framer AI',      description: 'Crea y publica sitios web completos desde una descripción de texto con diseño profesional automático. Se hizo conocido entre diseñadores por combinar la potencia de un constructor web profesional con generación IA, siendo el favorito de diseñadores que quieren publicar sin código.' },
  { name: 'Figma AI',       description: 'Funciones IA en Figma para generar prototipos, sugerir layouts y automatizar diseño de interfaces. Se hizo conocido por integrar IA directamente en la herramienta de diseño UI/UX más usada del mundo, automatizando tareas repetitivas que consumían horas.' },
  { name: 'QuillBot',       description: 'Parafraseador y resumidor IA con múltiples modos de escritura y corrector gramatical integrado. Se hizo conocido por ser la herramienta más usada por estudiantes universitarios para parafrasear textos, con más de 35 millones de usuarios activos.' },
  { name: 'Hemingway App',  description: 'Editor de texto que identifica frases complejas y mejora la claridad y legibilidad de tus escritos. Se hizo conocido por ser la herramienta favorita de periodistas y bloggers para escribir con claridad estilo Hemingway, siendo usado por los equipos de contenido de las mayores empresas del mundo.' },
  { name: 'Sudowrite',      description: 'Asistente de escritura creativa IA para novelistas con herramientas para expandir y desarrollar historias. Se hizo conocido por ser la primera herramienta IA diseñada específicamente para escritores de ficción, adoptada por autores publicados y ganadores de premios literarios.' },
  { name: 'Frase.io',       description: 'Investiga y escribe contenido SEO optimizado con IA analizando las SERPs en tiempo real. Se hizo conocida entre agencias SEO por generar briefs de contenido y artículos optimizados que combinan investigación real de competencia con generación IA.' },
  { name: 'MarketMuse',     description: 'Plataforma de estrategia de contenido IA que identifica brechas temáticas y oportunidades SEO. Se hizo conocida entre publishers y grandes medios digitales por ser la herramienta que garantiza autoridad temática analizando todo el contenido de un sitio.' },
  { name: 'Semrush AI',     description: 'Suite SEO completa con herramientas IA para investigación de palabras clave, auditorías y generación de contenido. Se hizo conocida por ser la suite SEO más completa del mundo y la herramienta de referencia de agencias digitales, con datos de más de 143 países.' },
  { name: 'AdCreative.ai',  description: 'Genera creatividades publicitarias optimizadas para conversión con IA para Meta, Google y más plataformas. Se hizo conocida por demostrar que sus creatividades generan un CTR significativamente mayor que las diseñadas por humanos, siendo adoptada por agencias de performance marketing.' },
  { name: 'Julius AI',      description: 'Analiza y visualiza datos subiendo archivos CSV o Excel y haciendo preguntas en lenguaje natural. Se hizo conocido por democratizar el análisis de datos, permitiendo que personas sin conocimientos de SQL o Python extraigan insights como si hablaran con un analista de datos.' },
  { name: 'MonkeyLearn',    description: 'Plataforma de machine learning sin código para clasificación de texto y análisis de sentimiento. Se hizo conocida por ser la herramienta que empresas sin equipos de data science usan para analizar automáticamente miles de reseñas, tickets de soporte y encuestas.' },
  { name: 'Obviously AI',   description: 'Construye y despliega modelos predictivos desde datos sin necesidad de conocimientos de ML. Se hizo conocida por permitir a equipos de ventas y marketing predecir churn, conversión y comportamiento de clientes sin un data scientist en el equipo.' },
  { name: 'Power BI Copilot', description: 'IA integrada en Power BI que genera reportes, narrativas y responde preguntas sobre tus datos. Se hizo conocido por llevar IA generativa a la herramienta de business intelligence más usada del mundo, permitiendo crear dashboards completos desde una descripción en lenguaje natural.' },
  { name: 'Semantic Scholar', description: 'Motor de búsqueda académica con IA que identifica papers relevantes y tendencias en investigación. Se hizo conocido por ser el buscador académico preferido de investigadores gracias a sus resúmenes automáticos con IA y su capacidad de mapear el impacto de citas científicas.' },
  { name: 'Consensus',      description: 'Motor de búsqueda científica IA que extrae conclusiones de millones de estudios peer-reviewed. Se hizo conocido entre médicos, investigadores y periodistas científicos por dar respuestas basadas 100% en evidencia científica revisada por pares, con las citas incluidas.' },
  { name: 'Scite.ai',       description: 'Analiza citas científicas para determinar si los estudios apoyan, contradicen o meramente mencionan un paper. Se hizo conocida en la comunidad científica por resolver el problema de saber si una investigación ha sido confirmada o refutada por estudios posteriores.' },
  { name: 'Duolingo Max',   description: 'Aprendizaje de idiomas potenciado por IA con explicaciones personalizadas y práctica conversacional con GPT-4. Se hizo conocido por ser la primera actualización de Duolingo que lleva la IA conversacional al aprendizaje de idiomas, permitiendo conversaciones libres con corrección instantánea.' },
  { name: 'Make',           description: 'Plataforma visual de automatización con capacidades IA para crear flujos de trabajo complejos. Se hizo conocida por ser la alternativa visual a Zapier favorita de agencias y power users por su modelo de precios más generoso y sus capacidades de automatizaciones complejas.' },
  { name: 'n8n',            description: 'Herramienta de automatización de código abierto con nodos de IA para flujos de trabajo avanzados. Se hizo conocida por ser la opción self-hosted favorita de developers que quieren automatizaciones sin límites ni costos de API, corriendo en su propio servidor.' },
  { name: 'Looka',          description: 'Crea logos y branding profesional con IA en minutos sin necesidad de conocimientos de diseño. Se hizo conocida por democratizar la identidad de marca, permitiendo a miles de pequeños negocios tener un logo profesional sin pagar a un diseñador.' },
  { name: 'Uizard',         description: 'Diseña aplicaciones y webs convirtiendo bocetos a mano o descripciones en prototipos interactivos con IA. Se hizo conocida entre product managers y founders por ser la forma más rápida de prototipar una app sin saber diseño ni código.' },
  { name: 'Khroma',         description: 'Generador de paletas de color IA que aprende tus preferencias para crear combinaciones únicas y personalizadas. Se hizo conocida entre diseñadores por ser la única herramienta de color que aprende el gusto específico de cada usuario en lugar de dar paletas genéricas.' },
  { name: 'Predis.ai',      description: 'Crea contenido para redes sociales con IA: imágenes, videos cortos y captions listos para publicar. Se hizo conocida entre social media managers por generar semanas de contenido completo en minutos, incluyendo el diseño visual y el copy optimizado para cada red.' },
  { name: 'Hootsuite AI',   description: 'Gestión de redes sociales con IA para generar captions, programar publicaciones y analizar rendimiento. Se hizo conocida por ser la plataforma de social media management más veterana del mercado e integrar IA para mantener su relevancia frente a competidores más nuevos.' },
  { name: 'Mailchimp AI',   description: 'Plataforma de email marketing con IA para segmentación predictiva, optimización de envíos y generación de contenido. Se hizo conocida por ser la herramienta de email marketing favorita de pequeños negocios del mundo y por democratizar el email marketing profesional.' },
  { name: 'Glean',          description: 'Búsqueda empresarial IA que conecta todas las apps de trabajo para encontrar información al instante. Se hizo conocida en empresas Fortune 500 por ser el "Google interno" que busca en Slack, Drive, Notion, Salesforce y todas las herramientas de trabajo simultáneamente.' },
  { name: 'Reclaim AI',     description: 'IA para gestión del tiempo que protege bloques de trabajo profundo y sincroniza calendarios automáticamente. Se hizo conocida entre profesionales de alto rendimiento por demostrar que recupera en promedio 40% del tiempo perdido en reuniones innecesarias.' },
  { name: 'Motion',         description: 'Planificador inteligente que organiza automáticamente tus tareas y reuniones en el calendario con IA. Se hizo conocido por ser el gestor de tareas que realmente prioriza y agenda por ti, siendo adoptado masivamente por solopreneurs y equipos remotos.' },
  { name: 'Mem AI',         description: 'App de notas con IA que organiza y conecta tu conocimiento automáticamente sin necesidad de carpetas. Se hizo conocida por ser la "segunda mente" IA que aprende de tus notas y conecta ideas relevantes sin que tengas que organizarlas manualmente.' },
  { name: 'Beautiful.ai',   description: 'Herramienta de presentaciones con diseño automático IA que mantiene la consistencia visual. Se hizo conocida en el mundo corporativo por generar presentaciones visualmente perfectas donde la IA ajusta el diseño automáticamente cuando cambias el contenido.' },
  { name: 'Tome',           description: 'Genera presentaciones narrativas completas con IA a partir de un tema o brief en segundos. Se hizo conocida entre creadores de contenido y speakers por generar decks con narrativa coherente y diseño profesional en segundos a partir de una sola idea.' },
  { name: 'Podcastle',      description: 'Graba, edita y publica podcasts con herramientas IA de mejora de voz y transcripción automática desde el navegador. Se hizo conocida por ser la única plataforma todo-en-uno para podcasters que incluye grabación, edición IA, transcripción y distribución en una sola herramienta.' },
  { name: 'Krisp',          description: 'Elimina el ruido de fondo en llamadas en tiempo real con IA, compatible con cualquier app de comunicación. Se hizo conocida durante la pandemia cuando millones de trabajadores remotos la adoptaron para sonar profesionales en reuniones desde casa, cafeterías y espacios ruidosos.' },
  { name: 'Resemble AI',    description: 'Clonación de voz IA en tiempo real con síntesis emocional para aplicaciones interactivas y videojuegos. Se hizo conocida en la industria de los videojuegos y el entretenimiento por permitir voces dinámicas y emocionales que se adaptan al contexto en tiempo real.' },
  { name: 'Play.ht',        description: 'Convierte texto a voz con más de 800 voces IA realistas en más de 140 idiomas y dialectos. Se hizo conocida por tener la biblioteca de voces más grande del mundo y por ser la herramienta favorita de publishers que convierten sus artículos en podcasts automáticamente.' },
  { name: 'LangChain',      description: 'Framework open source para construir aplicaciones con LLMs encadenando llamadas, agentes y fuentes de datos. Se hizo conocido por ser el framework más adoptado para construir aplicaciones de IA, con más de 80,000 estrellas en GitHub y siendo el estándar de la industria.' },
  { name: 'Replicate',      description: 'Corre modelos IA de código abierto en la nube con una simple API sin gestionar infraestructura. Se hizo conocida por ser la forma más fácil de acceder a miles de modelos open source con una sola API, siendo la puerta de entrada para developers que quieren experimentar con IA.' },
  { name: 'CodeLlama',      description: 'Modelo de código abierto de Meta especializado en generación y análisis de código, basado en Llama 2. Se hizo conocido por ser el modelo de código open source más capaz del mercado, ofreciendo capacidades similares a GPT-4 para tareas de programación de forma gratuita.' },
  { name: 'Lex.page',       description: 'Editor de texto con IA integrada que desbloquea el bloqueo del escritor y mejora textos en tiempo real. Se hizo conocido por ser el editor favorito de escritores y ensayistas que quieren IA como colaboradora sin reemplazar su voz ni su estilo propio.' },
  { name: 'Intercom Fin',   description: 'Chatbot IA de soporte al cliente que resuelve tickets automáticamente con alta tasa de resolución, basado en GPT-4. Se hizo conocido por ser el primer chatbot de soporte que realmente resuelve preguntas complejas sin escalar a humanos, cambiando el estándar del soporte IA.' },
  { name: 'Drift',          description: 'Plataforma de conversational marketing con IA para calificar leads y agendar reuniones automáticamente. Se hizo conocida por ser pionera en el concepto de "conversational marketing" y por ser la herramienta preferida de equipos de ventas B2B para capturar leads 24/7.' },
  { name: 'Tidio',          description: 'Plataforma de atención al cliente con chatbot IA Lyro que resuelve consultas automáticamente con alta precisión. Se hizo conocida entre e-commerces de tamaño medio por ser la alternativa más accesible a soluciones enterprise de chatbot, con resultados reales demostrados.' },
  { name: 'Voiceflow',      description: 'Diseña y despliega chatbots y asistentes de voz con IA sin necesidad de código. Se hizo conocida por ser la herramienta preferida de diseñadores de conversación y product managers para prototipar y publicar agentes conversacionales sin escribir una línea de código.' },
  { name: 'Lobe Chat',      description: 'Interfaz de chat IA de código abierto que soporta múltiples proveedores y modelos locales. Se hizo conocida por ser la interfaz open source más completa para conectar cualquier LLM, siendo el ChatGPT privado favorito de developers que quieren control total.' },
  { name: 'Character.ai',   description: 'Plataforma para crear y chatear con personajes IA con personalidades y contextos definidos. Se hizo conocida por ser viral entre Gen Z, con millones de usuarios creando y conversando con personajes de anime, celebridades y personajes de ficción generados por IA.' },
  { name: 'Pi',             description: 'Asistente IA personal de Inflection AI con conversación natural, empático y enfocado en el bienestar del usuario. Se hizo conocido por ser el asistente IA más "humano" del mercado, diseñado para escuchar y acompañar emocionalmente más que para ser productivo.' },
  { name: 'Canva AI',       description: 'Herramientas IA integradas en Canva: generación de imágenes, texto, presentaciones y fondos mágicos. Se hizo conocido por llevar el poder de la IA generativa a los 170 millones de usuarios de Canva, haciendo que crear diseños profesionales sea accesible para cualquier persona.' },
  { name: 'Fireflies.ai',   description: 'Notetaker IA para reuniones que transcribe, resume y permite buscar dentro de las conversaciones. Se hizo conocido por ser el bot de notas más adoptado en Zoom y Meet, con más de 300,000 empresas usándolo para no perder ningún acuerdo ni acción de reunión.' },
  { name: 'Khan Academy Khanmigo', description: 'Tutor IA de Khan Academy que guía estudiantes con preguntas socráticas sin dar las respuestas directamente. Se hizo conocido por demostrar cómo la IA puede mejorar la educación sin hacer trampa, siendo el modelo de IA educativa más respetado por pedagogos.' },
  { name: 'Coursera AI',    description: 'Plataforma de aprendizaje con asistente IA que personaliza recomendaciones de cursos y apoya el estudio. Se hizo conocida por sus certificados de Google, IBM y universidades Ivy League que son reconocidos globalmente para cambiar de carrera.' },
  { name: 'Duolingo Max',   description: 'Aprendizaje de idiomas potenciado por IA con explicaciones personalizadas y práctica conversacional con GPT-4. Se hizo conocido por ser la primera actualización de Duolingo que lleva IA conversacional al aprendizaje de idiomas, permitiendo conversaciones libres con corrección instantánea.' },
];

async function seed() {
  await mongoose.connect(process.env.MONGODB_URI || process.env.MONGO_URI);
  console.log('Connected to MongoDB\n');

  // 1. Insert new tools (skip if exists)
  let added = 0, skipped = 0;
  console.log('── Inserting new tools ──────────────────────');
  for (const tool of newTools) {
    const exists = await AITool.findOne({ name: tool.name });
    if (exists) {
      skipped++;
      console.log(`  SKIP  ${tool.name}`);
    } else {
      await AITool.create({ ...tool, isActive: true, featured: false });
      added++;
      console.log(`  ADD   ${tool.name}`);
    }
  }

  // 2. Update descriptions of existing tools
  let updated = 0;
  console.log('\n── Updating descriptions ────────────────────');
  for (const u of updates) {
    const result = await AITool.updateOne(
      { name: u.name },
      { $set: { description: u.description } }
    );
    if (result.matchedCount > 0) {
      updated++;
      console.log(`  UPDATE  ${u.name}`);
    } else {
      console.log(`  NOT FOUND  ${u.name}`);
    }
  }

  console.log(`\nDone: ${added} added, ${skipped} skipped, ${updated} descriptions updated`);
  await mongoose.disconnect();
}

seed().catch(err => { console.error(err); process.exit(1); });
